import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ReduxStoreProvider } from "@/lib/redux/ReduxStoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ReduxStoreProvider>
        <body className={cn(inter.className, "antialiased p-8 m-auto")}>
          {children}
        </body>
      </ReduxStoreProvider>
    </html>
  );
}
